<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="expressions"
    nsURI="http://www.orcas.org/spec/iocl/1.0/expressions" nsPrefix="expressions">
  <eSubpackages name="emof" nsURI="http://www.orcas.org/spec/iocl/1.0/emof" nsPrefix="emof">
    <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="#//emof/Type">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttribute" upperBound="-1"
          eType="#//emof/Property" containment="true" eOpposite="#//emof/Property/class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" upperBound="-1"
          eType="#//emof/Operation" containment="true" eOpposite="#//emof/Operation/class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" upperBound="-1"
          eType="#//emof/Class"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="#//emof/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="#//emof/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true" eSuperTypes="#//emof/Object">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tag" upperBound="-1"
          eType="#//emof/Tag" eOpposite="#//emof/Tag/element"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" upperBound="-1"
          eType="#//emof/Comment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Tag" eSuperTypes="#//emof/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="element" upperBound="-1"
          eType="#//emof/Element" eOpposite="#//emof/Element/tag"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//emof/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//emof/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" upperBound="-1"
          eType="#//emof/EnumerationLiteral" containment="true" eOpposite="#//emof/EnumerationLiteral/enumeration"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//emof/Element">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Extent" eSuperTypes="#//emof/Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="Object"/>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//emof/MultiplicityElement #//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1"
          eType="#//emof/Class" transient="true" eOpposite="#//emof/Class/ownedOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" upperBound="-1"
          eType="#//emof/Parameter" containment="true" eOpposite="#//emof/Parameter/operation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="raisedException" upperBound="-1"
          eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="#//emof/Integer"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="#//emof/UnlimitedNatural"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Package" eSuperTypes="#//emof/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedType" upperBound="-1"
          eType="#//emof/Type" containment="true" eOpposite="#//emof/Type/package"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPackage" upperBound="-1"
          eType="#//emof/Package" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true" eSuperTypes="#//emof/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="package" lowerBound="1"
          eType="#//emof/Package" transient="true" eOpposite="#//emof/Package/ownedType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//emof/MultiplicityElement #//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" eType="#//emof/Operation"
          transient="true" eOpposite="#//emof/Operation/ownedParameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//emof/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="enumeration" eType="#//emof/Enumeration"
          transient="true" eOpposite="#//emof/Enumeration/ownedLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//emof/MultiplicityElement #//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="class" lowerBound="1"
          eType="#//emof/Class" transient="true" eOpposite="#//emof/Class/ownedAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//emof/Property"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isComposite" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isId" eType="#//emof/Boolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//emof/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" eSuperTypes="#//emof/DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="URIExtent" eSuperTypes="#//emof/Extent"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean" instanceClassName="java.lang.Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String" instanceClassName="java.lang.String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="UnlimitedNatural" instanceClassName="java.lang.Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Integer" instanceClassName="java.lang.Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Real" instanceClassName="java.lang.Float"/>
    <eClassifiers xsi:type="ecore:EClass" name="Comment" eSuperTypes="#//emof/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" upperBound="-1"
          eType="#//emof/NamedElement"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="imperativeocl" nsURI="http://www.orcas.org/spec/iocl/1.0/imperativeocl"
      nsPrefix="imperativeocl">
    <eClassifiers xsi:type="ecore:EClass" name="AssignExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//ocl/OclExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReset" eType="#//emof/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BlockExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SwitchExp" eSuperTypes="#//ocl/CallExp #//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="alternativePart" upperBound="-1"
          eType="#//imperativeocl/AltExp" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elsePart" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableInitExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" lowerBound="1"
          eType="#//ocl/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="withResult" eType="#//emof/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WhileExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComputeExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnedElement" lowerBound="1"
          eType="#//ocl/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AltExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnlinkExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BreakExp" eSuperTypes="#//imperativeocl/ImperativeExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="TryExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tryBody" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="catchClause" upperBound="-1"
          eType="#//imperativeocl/CatchExp" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RaiseExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="exception" lowerBound="1"
          eType="#//emof/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContinueExp" eSuperTypes="#//imperativeocl/ImperativeExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="ForExp" eSuperTypes="#//imperativeocl/ImperativeLoopExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="Typedef" eSuperTypes="#//emof/Class">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base" lowerBound="1"
          eType="#//emof/Type"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstantiationExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="instantiatedClass" lowerBound="1"
          eType="#//emof/Class"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extent" eType="#//ocl/Variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictionaryType" eSuperTypes="#//ocl/CollectionType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="keyType" eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictLiteralExp" eSuperTypes="#//ocl/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
          eType="#//imperativeocl/DictLiteralPart" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DictLiteralPart" eSuperTypes="#//emof/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//ocl/OclExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateParameterType" eSuperTypes="#//emof/Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="specification" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LogExp" eSuperTypes="#//ocl/OperationCallExp #//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AssertExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//imperativeocl/SeverityKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="log" eType="#//imperativeocl/LogExp"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assertion" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="SeverityKind">
      <eLiterals name="error"/>
      <eLiterals name="warning" value="1"/>
      <eLiterals name="fatal" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeLoopExp" abstract="true"
        eSuperTypes="#//ocl/LoopExp #//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeIterateExp" eSuperTypes="#//imperativeocl/ImperativeLoopExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ocl/Variable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ImperativeExpression" abstract="true"
        eSuperTypes="#//ocl/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnpackExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetVariable" lowerBound="1"
          upperBound="-1" eType="#//ocl/Variable" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedTupleType" eSuperTypes="#//emof/Class">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" upperBound="-1"
          eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedTupleLiteralExp" eSuperTypes="#//ocl/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
          eType="#//imperativeocl/OrderedTupleLiteralPart" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedTupleLiteralPart" eSuperTypes="#//emof/Element">
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ListType" eSuperTypes="#//ocl/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="CatchExp" eSuperTypes="#//imperativeocl/ImperativeExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exception" upperBound="-1"
          eType="#//emof/Type"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="ocl" nsURI="http://www.orcas.org/spec/iocl/1.0/ocl" nsPrefix="ocl">
    <eClassifiers xsi:type="ecore:EClass" name="BooleanLiteralExp" eSuperTypes="#//ocl/PrimitiveLiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanSymbol" eType="#//emof/Boolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CallExp" abstract="true" eSuperTypes="#//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ocl/OclExpression"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
      <eLiterals name="Set"/>
      <eLiterals name="OrderedSet" value="1"/>
      <eLiterals name="Bag" value="2"/>
      <eLiterals name="Sequence" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OclExpression" abstract="true" eSuperTypes="#//emof/TypedElement #//util/Visitable"/>
    <eClassifiers xsi:type="ecore:EClass" name="UnlimitedNaturalExp" eSuperTypes="#//ocl/NumericLiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="symbol" eType="#//emof/UnlimitedNatural"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IfExp" eSuperTypes="#//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="thenExpression" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LetExp" eSuperTypes="#//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="in" lowerBound="1" eType="#//ocl/OclExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
          eType="#//ocl/Variable" containment="true" eOpposite="#//ocl/Variable/letExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initExpression" eType="#//ocl/OclExpression"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="letExp" eType="#//ocl/LetExp"
          transient="true" eOpposite="#//ocl/LetExp/variable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindParameter" eType="#//emof/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyCallExp" eSuperTypes="#//ocl/FeaturePropertyCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredProperty" eType="#//emof/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="VariableExp" eSuperTypes="#//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredVariable" eType="#//ocl/Variable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TypeExp" eSuperTypes="#//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredType" eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LoopExp" abstract="true" eSuperTypes="#//ocl/CallExp #//ocl/OclExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="iterator" upperBound="-1"
          eType="#//ocl/Variable" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IteratorExp" eSuperTypes="#//ocl/LoopExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringLiteralExp" eSuperTypes="#//ocl/PrimitiveLiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringSymbol" eType="#//emof/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteralExp" eSuperTypes="#//ocl/NumericLiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="integerSymbol" eType="#//emof/Integer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationCallExp" eSuperTypes="#//ocl/FeaturePropertyCall">
      <eStructuralFeatures xsi:type="ecore:EReference" name="argument" upperBound="-1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredOperation" eType="#//emof/Operation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RealLiteralExp" eSuperTypes="#//ocl/NumericLiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="realSymbol" eType="#//emof/Real"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExp" abstract="true" eSuperTypes="#//ocl/OclExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="IterateExp" eSuperTypes="#//ocl/LoopExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//ocl/Variable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveLiteralExp" abstract="true"
        eSuperTypes="#//ocl/LiteralExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="NumericLiteralExp" abstract="true"
        eSuperTypes="#//ocl/PrimitiveLiteralExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralExp" eSuperTypes="#//ocl/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ocl/CollectionKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
          eType="#//ocl/CollectionLiteralPart" containment="true" eOpposite="#//ocl/CollectionLiteralPart/collectionLiteralExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionLiteralPart" abstract="true"
        eSuperTypes="#//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="collectionLiteralExp"
          lowerBound="1" eType="#//ocl/CollectionLiteralExp" transient="true" eOpposite="#//ocl/CollectionLiteralExp/part"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionItem" eSuperTypes="#//ocl/CollectionLiteralPart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionRange" eSuperTypes="#//ocl/CollectionLiteralPart">
      <eStructuralFeatures xsi:type="ecore:EReference" name="first" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="last" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralExp" eSuperTypes="#//ocl/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="part" upperBound="-1"
          eType="#//ocl/TupleLiteralPart" containment="true" eOpposite="#//ocl/TupleLiteralPart/tupleLiteralExp"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullLiteralExp" eSuperTypes="#//ocl/LiteralExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionInOcl" eSuperTypes="#//ocl/OpaqueExpression">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bodyExpression" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ocl/Variable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resultVariable" eType="#//ocl/Variable"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterVariable" eType="#//ocl/Variable"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpaqueExpression"/>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidLiteralExp" eSuperTypes="#//ocl/LiteralExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeaturePropertyCall" abstract="true"
        eSuperTypes="#//ocl/CallExp"/>
    <eClassifiers xsi:type="ecore:EClass" name="TupleLiteralPart" eSuperTypes="#//emof/TypedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="tupleLiteralExp" eType="#//ocl/TupleLiteralExp"
          transient="true" eOpposite="#//ocl/TupleLiteralExp/part"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" eType="#//emof/Property"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//ocl/OclExpression" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BagType" eSuperTypes="#//ocl/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionType" abstract="true" eSuperTypes="#//emof/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementType" eType="#//emof/Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumLiteralExp" eSuperTypes="#//ocl/LiteralExp">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referredEnumLiteral"
          eType="#//emof/EnumerationLiteral"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InvalidType" eSuperTypes="#//emof/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="OrderedSetType" eSuperTypes="#//ocl/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceType" eSuperTypes="#//ocl/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="SetType" eSuperTypes="#//ocl/CollectionType"/>
    <eClassifiers xsi:type="ecore:EClass" name="TupleType" eSuperTypes="#//emof/Class #//emof/DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="VoidType" eSuperTypes="#//emof/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="AnyType" eSuperTypes="#//emof/Class #//emof/Type"/>
  </eSubpackages>
  <eSubpackages name="util" nsURI="http://www.orcas.org/spec/iocl/1.0/util" nsPrefix="util">
    <eClassifiers xsi:type="ecore:EClass" name="Visitable">
      <eOperations name="accept">
        <eGenericType eTypeParameter="#//util/Visitable/accept/T"/>
        <eTypeParameters name="T"/>
        <eTypeParameters name="V">
          <eBounds eClassifier="#//util/Visitor"/>
        </eTypeParameters>
        <eParameters name="v">
          <eGenericType eTypeParameter="#//util/Visitable/accept/V"/>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Visitor">
      <eTypeParameters name="T"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
